version: '2.1'
services:
    db:
        image: mysql:5.7
        env_file: .env
        volumes:
            - "db_volume:/var/lib/mysql"
        restart: always

    server:
        build:
            context: ./
        env_file: .env
        ports:
            - "${ZBX_SERVER_PORT}:10051"
        volumes:
            - "./data:/usr/lib/zabbix"
        privileged: true
        restart: always

    client:
        image: zabbix/zabbix-agent
        env_file: .env
        ports:
          - "${ZBX_CLIENT_PORT}:10050"
        privileged: true
        restart: always

    front:
        image: zabbix/zabbix-web-nginx-mysql
        env_file: .env
        ports:
            - "${ZBX_FRONT_PORT}:80"
        restart: always

volumes:
    db_volume:
        driver: local
